### ISSUE TITLE
gpg ファイルの作成に失敗する

### ISSUE THREAD

**Issue by sk-ys** [ishikawa999/redmine_development_docker#14]
Dockerfile の `FROM mcr.microsoft.com/vscode/devcontainers/ruby:$RUBY_VERSION` で取得される最新のイメージでは、OSが `Debian GNU/Linux 11 (bullseye)` となっており、`/etc/apt/keyrings` ディレクトリが存在しないために `/etc/apt/keyrings/nodesource.gpg` の作成に失敗するようです。

エラーログ（抜粋）:
```
8.011 gpg: can't create
[2024-03-03T00:01:57.958Z]  '/etc/apt/keyrings/nodesource.gpg': No such file or directory
8.011 gpg: no valid OpenPGP data found.
8.011 gpg: dearmoring failed: No such file or directory
8.126 (23) Failed writing body
8.131 deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
8.186 Hit:1 http://deb.debian.org/debian bullseye InRelease
8.209 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
8.236 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
8.277 Hit:4 https://dl.yarnpkg.com/debian stable InRelease
8.313 Get:5 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
8.385 Err:5 https://deb.nodesource.com/node_20.x nodistro InRelease
8.385   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
8.388 Reading package lists...
8.671 W: GPG error: https://deb.nodesource.com/node_20.x nodistro InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
8.671 E: The repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' is not signed.
------
failed to solve: process "/bin/sh -c /setup.sh" did not complete successfully: exit code: 100
```

さしあたり `/scripts/setup.sh` の nodejs インストールコマンド群の前に `mkdir /etc/apt/keyrings` を挿入することで動くことは確認できたのですが、これが最適解なのかわからないため報告までにいたします。

```diff
 scripts/setup.sh | 1 +
 1 file changed, 1 insertion(+)

diff --git a/scripts/setup.sh b/scripts/setup.sh
index 6decb11..eaa9ec2 100644
--- a/scripts/setup.sh
+++ b/scripts/setup.sh
@@ -32,6 +32,7 @@ update-locale
 locale-gen ja_JP.UTF-8
 localedef -f UTF-8 -i ja_JP ja_JP
 
+mkdir /etc/apt/keyrings
 apt-get update && apt-get install -y ca-certificates curl gnupg
 curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
 NODE_MAJOR=20
```

**Comment by ishikawa999** [comment]
報告ありがとうございます。FROM mcr.microsoft.com/vscode/devcontainers/ruby:3-bullseye にして動かすことで再現できました。最近は3.3のbookwormで動かしていたため問題に気づいておらず...(bookwormでは/etc/apt/keyringsディレクトリがあり問題なく動いていました)

**Comment by ishikawa999** [comment]
色々調べてみたところ、/etc/apt/keyringsは鍵を置くために推奨されているディレクトリで、bullseyeなどの時点ではまだ存在していないようです。あくまでも置き場の一つなので、ない場合は/etc/apt/keyringsを作って置くので問題無さそうです。

https://docs.docker.com/engine/install/debian/#install-using-the-repository
でも、 `install -m 0755 -d /etc/apt/keyrings` で/etc/apt/keyringsを作っています。

**Comment by ishikawa999** [comment]
私がコミットしてしまっても良いのですが、せっかくここまで調べていただいたので @sk-ys さんの活動としてちゃんと残るようにプルリクをいただいてマージするのが良いかなと思います。お手隙の時で大丈夫です

**Comment by sk-ys** [comment]
コメント＆解析ありがとうございます。
では初めのdiffの通りプルリクエストを出すようにいたします。
（原因を探る途中で https://deb.nodesource.com/ は始めて知りました。勉強になりました。）
別の話で、私は特に何も考えず `.env` 初期値のRuby2.7のまま使用させていただいたのですが、初期値も見直したほうが良いのでしょうかね…？

**Comment by ishikawa999** [comment]
> 別の話で、私は特に何も考えず .env 初期値のRuby2.7のまま使用させていただいたのですが、初期値も見直したほうが良いのでしょうかね…？

trunkのRedmineではすでにRuby2.7のサポートをやめている（ruby '>= 3.0.0', '< 3.4.0'）ため、Ruby3.0 までは上げた方が良さそうです

**Comment by sk-ys** [comment]
ありがとうございます！
